### ISSUE TITLE
Build fails in lts/boron

### ISSUE THREAD

**Issue by elhoyos** [dachev/node-cld#55]
I'm unable to build or use node-cld@2.5.1 in node@6.9.5 (Linux).

<details><summary>Stack trace</summary><p>

```
> cld@2.5.1 install /my_home/my_app/node_modules/cld
> node-gyp rebuild

make: Entering directory '/my_home/my_app/node_modules/cld/build'
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cldutil.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cldutil_shared.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/compact_lang_det.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/compact_lang_det_hint_code.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/compact_lang_det_impl.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/debug.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/fixunicodevalue.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_entities.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_language.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_ulscript.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/getonescriptspan.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/lang_script.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/offsetmap.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/scoreonescriptspan.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/tote.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/utf8statetable.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_cjk_uni_prop_80.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_cjk_compatible.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_cjk_delta_bi_32.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_distinct_bi_0.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_quad0122.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_deltaocta0122.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_deltaoctachrome.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_distinctocta0122.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_distinctoctachrome.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_quadchrome_16.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_quadchrome_2.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_score_quad_octa_0122.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_score_quad_octa_2.o
  AR(target) Release/obj.target/deps/cld/cld-c.a
  COPY Release/cld-c.a
  CXX(target) Release/obj.target/cld/src/constants.o
  CXX(target) Release/obj.target/cld/src/cld.o
../src/cld.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE NodeCld::Detect(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/cld.cc:14:104: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::String>)’
     v8::String::Utf8Value text(v8::Isolate::GetCurrent(), Nan::To<v8::String>(info[0]).ToLocalChecked());
                                                                                                        ^
In file included from /my_home/.node-gyp/6.9.5/include/node/node.h:42:0,
                 from ../../nan/nan.h:54,
                 from ../src/cld.cc:8:
/my_home/.node-gyp/6.9.5/include/node/v8.h:2438:5: note: candidate: v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Value&)
     Utf8Value(const Utf8Value&);
     ^~~~~~~~~
/my_home/.node-gyp/6.9.5/include/node/v8.h:2438:5: note:   candidate expects 1 argument, 2 provided
/my_home/.node-gyp/6.9.5/include/node/v8.h:2428:14: note: candidate: v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)
     explicit Utf8Value(Local<v8::Value> obj);
              ^~~~~~~~~
/my_home/.node-gyp/6.9.5/include/node/v8.h:2428:14: note:   candidate expects 1 argument, 2 provided
../src/cld.cc:26:112: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::String>)’
     v8::String::Utf8Value languageHint(v8::Isolate::GetCurrent(), Nan::To<v8::String>(info[2]).ToLocalChecked());
                                                                                                                ^
In file included from /my_home/.node-gyp/6.9.5/include/node/node.h:42:0,
                 from ../../nan/nan.h:54,
                 from ../src/cld.cc:8:
/my_home/.node-gyp/6.9.5/include/node/v8.h:2438:5: note: candidate: v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Value&)
     Utf8Value(const Utf8Value&);
     ^~~~~~~~~
/my_home/.node-gyp/6.9.5/include/node/v8.h:2438:5: note:   candidate expects 1 argument, 2 provided
/my_home/.node-gyp/6.9.5/include/node/v8.h:2428:14: note: candidate: v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)
     explicit Utf8Value(Local<v8::Value> obj);
              ^~~~~~~~~
/my_home/.node-gyp/6.9.5/include/node/v8.h:2428:14: note:   candidate expects 1 argument, 2 provided
../src/cld.cc:27:112: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::String>)’
     v8::String::Utf8Value encodingHint(v8::Isolate::GetCurrent(), Nan::To<v8::String>(info[3]).ToLocalChecked());
                                                                                                                ^
In file included from /my_home/.node-gyp/6.9.5/include/node/node.h:42:0,
                 from ../../nan/nan.h:54,
                 from ../src/cld.cc:8:
/my_home/.node-gyp/6.9.5/include/node/v8.h:2438:5: note: candidate: v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Value&)
     Utf8Value(const Utf8Value&);
     ^~~~~~~~~
/my_home/.node-gyp/6.9.5/include/node/v8.h:2438:5: note:   candidate expects 1 argument, 2 provided
/my_home/.node-gyp/6.9.5/include/node/v8.h:2428:14: note: candidate: v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)
     explicit Utf8Value(Local<v8::Value> obj);
              ^~~~~~~~~
/my_home/.node-gyp/6.9.5/include/node/v8.h:2428:14: note:   candidate expects 1 argument, 2 provided
../src/cld.cc:28:107: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::String>)’
     v8::String::Utf8Value tldHint(v8::Isolate::GetCurrent(), Nan::To<v8::String>(info[4]).ToLocalChecked());
                                                                                                           ^
In file included from /my_home/.node-gyp/6.9.5/include/node/node.h:42:0,
                 from ../../nan/nan.h:54,
                 from ../src/cld.cc:8:
/my_home/.node-gyp/6.9.5/include/node/v8.h:2438:5: note: candidate: v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Value&)
     Utf8Value(const Utf8Value&);
     ^~~~~~~~~
/my_home/.node-gyp/6.9.5/include/node/v8.h:2438:5: note:   candidate expects 1 argument, 2 provided
/my_home/.node-gyp/6.9.5/include/node/v8.h:2428:14: note: candidate: v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)
     explicit Utf8Value(Local<v8::Value> obj);
              ^~~~~~~~~
/my_home/.node-gyp/6.9.5/include/node/v8.h:2428:14: note:   candidate expects 1 argument, 2 provided
../src/cld.cc:29:108: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::String>)’
     v8::String::Utf8Value httpHint(v8::Isolate::GetCurrent(), Nan::To<v8::String>(info[5]).ToLocalChecked());
                                                                                                            ^
In file included from /my_home/.node-gyp/6.9.5/include/node/node.h:42:0,
                 from ../../nan/nan.h:54,
                 from ../src/cld.cc:8:
/my_home/.node-gyp/6.9.5/include/node/v8.h:2438:5: note: candidate: v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Value&)
     Utf8Value(const Utf8Value&);
     ^~~~~~~~~
/my_home/.node-gyp/6.9.5/include/node/v8.h:2438:5: note:   candidate expects 1 argument, 2 provided
/my_home/.node-gyp/6.9.5/include/node/v8.h:2428:14: note: candidate: v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)
     explicit Utf8Value(Local<v8::Value> obj);
              ^~~~~~~~~
/my_home/.node-gyp/6.9.5/include/node/v8.h:2428:14: note:   candidate expects 1 argument, 2 provided
cld.target.mk:102: recipe for target 'Release/obj.target/cld/src/cld.o' failed
make: *** [Release/obj.target/cld/src/cld.o] Error 1
make: Leaving directory '/my_home/my_app/node_modules/cld/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.14.44-32.39.amzn1.x86_64
gyp ERR! command "/usr/local/nvm/versions/node/v6.9.5/bin/node" "/usr/local/nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /my_home/my_app/node_modules/cld
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

</p></details>

At this moment I am unable to upgrade to the latest lts/boron and confirm there too.

https://github.com/dachev/node-cld/pull/53 looks like worth looking at. I wish I could help further.

Question: although node@6.x is End-Of-Life, [ad91d3](https://github.com/dachev/node-cld/commit/ad91d31d57d2c11f246fbaec4ec76f0f6d3953d0#diff-180360612c6b8c4ed830919bbb4dd459) suggests you are expecting to support it. Is this assumption correct?

**Comment by dachev** [comment]
@elhoyos you can ignore the appveyor.yml file. This snuck in with a PR and I did not object because Windows CI was already broken and I plan on working on it next.

2.5.x is supposed to be compatible only with node >= 12 (see 1c10b8e). Meanwhile, 2.4.9 is supposed to be used with prior node versions (see 1e52a93).

Could this be an npm bug, or I am missing something?

**Comment by elhoyos** [comment]
>Could this be an npm bug, or I am missing something?

I know nothing useful from gyp and node.js native addons to help  :( But I can tell you this: 2.5.1 builds ok in lts/carbon (v8.x) :)

By the way, have you considered following semver and have this move to node >= 12 to be a major release?

**Comment by dachev** [comment]
> I know nothing useful from gyp and node.js native addons to help :( But I can tell you this: 2.5.1 builds ok in lts/carbon (v8.x) :)
This is not about gyp or native. 2.4.9 declares support for older node versions, while 2.5.x declares support for node 12. My understanding is that npm should pick the right one for your version of node.

> By the way, have you considered following semver and have this move to node >= 12 to be a major release?
I am not sure I follow. Can you paste the relevant semversion spec?

**Comment by elhoyos** [comment]
Latest lts/boron version (6.17.1) also fails. Nothing to do there.

>My understanding is that npm should pick the right one for your version of node.

Not quite. According to the docs, npm will follow strictly only if the user passes the `engine-strict` flag, and that is not happening in most cases for sure. There used to be an `engineStrict` field in the package.json but it got removed at npm@3.0.0. So, by default, the `engines` field is advisory only.

If you really want npm to pick the right version and to go easy on your users you can try following semantic versioning, because npm does follow the convention strictly. Simply put, you follow a meaningful schema to version your library: major.minor.patch (e.g. 2.5.1), and users specify the range of versions they want to install in their package.json file. In the case of our interest, stop supporting node < 12.x is a major change that will break for some or most of your current users, then you augment the major part of the version that drop the support from 2.4.9 to 3.0.0, and your <=2.4.9 users will remain there until they realize they want to upgrade.

More info here: https://docs.npmjs.com/misc/semver

In the current state of things, you could revert the 2.5.x changes (i.e. 2.5.0 & 2.5.1 in semver ranges), and cherry-pick those commits into a new 3.0.0 version.

**Comment by dachev** [comment]
I was asking about the specific semver spec you are referring to because the only relevant one I see is #8 here (https://semver.org/):
> Major version X (X.y.z | X > 0) MUST be incremented if any backward incompatible changes are introduced to the public API.

Sounds like you are asking for pragmatic versioning instead :-)

**Comment by elhoyos** [comment]
😆 Yes, that's the specific spec. I have had good experiences with semver in general and have never heard about pragmatic versioning.

I have to admit the public API of node-cld has not changed at all and it kind of deviates from the specific semver spec. I understand the engine is also part of the "public API". Sometimes we ignore other important things related to the "public API" like the platform (Linux, Mac, Windows) because the runtime (node.js) abstract that for us.

Pragmatic versioning seems like a fit for the change with the ["Disruptive Modifications" bit](https://pragver.github.io/spec/#disruptive-modifications), but I do not know if it is too much. In node-cld I do not see the need to communicate that.
