### ISSUE TITLE
Node 12 compile issue on Windows 32 bit

### ISSUE THREAD

**Issue by anteburazer** [dachev/node-cld#57]
Hello

I encountered an incompatibility while building with Node 12 on 32bit Windows machine.
Here are the logs.

```
     [exec] d:\a\_work\428\s\.temp\node_headers\include\node\v8.h(8207): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\cld.cc) [D:\a\_work\428\s\node_modules\cld\build\cld.vcxproj]
     [exec]   d:\a\_work\428\s\.temp\node_headers\include\node\v8.h(6668): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\cld.cc)
     [exec] d:\a\_work\428\s\.temp\node_headers\include\node\v8.h(8216): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\cld.cc) [D:\a\_work\428\s\node_modules\cld\build\cld.vcxproj]
     [exec]   d:\a\_work\428\s\.temp\node_headers\include\node\v8.h(6668): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\cld.cc)
     [exec] d:\a\_work\428\s\node_modules\nan\nan_converters_43_inl.h(22): error C2664: 'v8::Local<v8::Boolean> v8::Value::ToBoolean(void) const': cannot convert argument 1 from 'v8::Local<v8::Context>' to 'v8::Isolate *' (compiling source file ..\src\cld.cc) [D:\a\_work\428\s\node_modules\cld\build\cld.vcxproj]
     [exec]   d:\a\_work\428\s\node_modules\nan\nan_converters_43_inl.h(22): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called (compiling source file ..\src\cld.cc)
     [exec] d:\a\_work\428\s\node_modules\nan\nan_converters_43_inl.h(22): error C2228: left of '.FromMaybe' must have class/struct/union (compiling source file ..\src\cld.cc) [D:\a\_work\428\s\node_modules\cld\build\cld.vcxproj]
     [exec] d:\a\_work\428\s\node_modules\nan\nan_converters_43_inl.h(40): error C2664: 'bool v8::Value::BooleanValue(void) const': cannot convert argument 1 from 'v8::Local<v8::Context>' to 'v8::Isolate *' (compiling source file ..\src\cld.cc) [D:\a\_work\428\s\node_modules\cld\build\cld.vcxproj]
     [exec]   d:\a\_work\428\s\node_modules\nan\nan_converters_43_inl.h(40): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called (compiling source file ..\src\cld.cc)
     [exec] d:\a\_work\428\s\node_modules\nan\nan_object_wrap.h(24): error C2039: 'IsNearDeath': is not a member of 'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>' [D:\a\_work\428\s\node_modules\cld\build\cld.vcxproj]
     [exec]           with
     [exec]           [
     [exec]               T=v8::Object
     [exec]           ] (compiling source file ..\src\cld.cc)
     [exec]   D:\a\_work\428\s\node_modules\nan\nan.h(1920): note: see declaration of 'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>'
     [exec]           with
     [exec]           [
     [exec]               T=v8::Object
     [exec]           ] (compiling source file ..\src\cld.cc)
     [exec] d:\a\_work\428\s\node_modules\nan\nan_object_wrap.h(127): error C2039: 'IsNearDeath': is not a member of 'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>' [D:\a\_work\428\s\node_modules\cld\build\cld.vcxproj]
     [exec]           with
     [exec]           [
     [exec]               T=v8::Object
     [exec]           ] (compiling source file ..\src\cld.cc)
     [exec]   D:\a\_work\428\s\node_modules\nan\nan.h(1920): note: see declaration of 'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>'
     [exec]           with
     [exec]           [
     [exec]               T=v8::Object
     [exec]           ] (compiling source file ..\src\cld.cc)
     [exec] gyp ERR! build error 
     [exec] gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
     [exec] gyp ERR! stack     at ChildProcess.onExit (C:\Apps\nodejs\8.11.2\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
     [exec] gyp ERR! stack     at emitTwo (events.js:126:13)
     [exec] gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
     [exec] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
     [exec] gyp ERR! System Windows_NT 10.0.17134
     [exec] gyp ERR! command "C:\\Apps\\nodejs\\8.11.2\\node.exe" "C:\\Apps\\nodejs\\8.11.2\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
```

**Comment by dachev** [comment]
@anteburazer Thanks for the heads up. This should be fixed in 2.6.0
